name: comment example

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hey Contributor! You can start working on the issue. Good luck!
              Please comment `/assign` to get this issue assigned to you.
              Don't forget to star the repository!'
            })
