name: comment example

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: jungwinter/comment@v1
        id: create
        with:
          type: create
          body: "- [ ] Run tests"
          issue_number: ${{ github.event.issue.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update comment
        uses: jungwinter/comment@v1
        with:
          type: edit
          body: "- [x] Run tests"
          comment_id: ${{ steps.create.outputs.id }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete comment
        uses: jungwinter/comment@v1
        with:
          type: delete
          comment_id: ${{ steps.create.outputs.id }}
          token: ${{ secrets.GITHUB_TOKEN }}
